### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/example-apps#12]
@joewagner since all of these have been moved to their own `example-` repo, should we deprecate / read-only this one?

**Comment by joewagner** [comment]
@dtbuchholz  that's a good idea. I don't have permissions needed to make this read-only, maybe @carsonfarmer can do that?
Does it make sense to put something in this README that mentions this is depreciated and points to  the new repos?
Or, maybe we can delete this repo entirely?

**Comment by dtbuchholz** [comment]
Ahh, gotcha. Same. And honestly, I don't see anything wrong with deleting it entirely. There might be some really old links that reference the repo in a Tweet, but docs shouldn't have any issues with that.

**Comment by joewagner** [comment]
@carsonfarmer I don't have the permission to delete this repo.  Do you wanna do that? And are you able to do that?

**Comment by carsonfarmer** [comment]
Ooop, missed this. Yes I can delete.
